apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-${ENV}
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: ${CFG_GIT_REPO}
      revision: main
      directories:
      # This looks for any app that has an overlay for the specific ENV
      - path: kustomize/*/overlays/${ENV}
  template:
    metadata:
      # Result: client-qas, hasura-qas, etc.
      name: '{{path[1]}}-{{path[3]}}' 
    spec:
      project: default
      source:
        repoURL: ${CFG_GIT_REPO}
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        # Deploys to namespace 'qas', 'int', or 'prd'
        namespace: ${NAMESPACE}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

